[core]
address    = "10.100.100.1:50051"
username   = "jet"
passwd     = "Passw0rd"
clientid   = "42"
jetTimeout = 10

localPref  = 200
routePref  = 10
asPathStr  = ""
originator = "10.255.255.3"
cluster    = "10.255.255.7"

[[route]]
prefix = "10.123.0.0"
length = 24
nexthops = ["10.0.0.1", "10.0.0.2", "10.0.0.3", "10.0.0.4"]

[[route]]
prefix = "10.123.1.0"
length = 24
nexthops = ["10.0.0.1", "10.0.0.2", "10.0.0.3", "10.0.0.4"]
